<div id='credits'>
    <div class='git'>
        <div class='logo'>
            <a href='http://github.com/dashee-bot/dashee' target='_blank'>
                <img src='/images/gitlogo/mark32.png' />
            </a>
        </div>
        <div class='text'>
            <div class='info'>Dashee on Github</div>
            <div class='link'>
                <a href='http://github.com/dashee-bot/dashee' target='_blank'>
                    http://github.com/dashee-bot/dashee
                </a>
            </div>
        </div>
    </div>
    <div class='copyright'>
        &copy; <?php echo date("Y"); ?>, Dashee
    </div>
</div>
