<div class='download'>
    <div class='clone'>
        <div class='image'>
            <img src='/images/gitlogo/mark64.png' />
        </div>
        <div class='text'>
            <h2>Get started by cloning the code</h2>
            <pre>$ git clone https://github.com/dashee-bot/dashee</pre>
            <p>Read our <a href='https://github.com/dashee-bot/dashee/wiki/Installing' target="_blank">installation instructions</a> to get started</p>
        </div>
    </div>    

    <div class='releases'>
        <h1>Packaged tag releases</h1>
        <?php foreach ($this->releases as $release): ?>
            <div class='release'>
                <div class='package'>
                    <div class='tag'><?php print $release->tag_name; ?></div>
                    <div class='info'>
                        <h3 class='name'><?php print $release->name; ?></h3>
                        <ul class='small-text'>
                            <li><?php print Application_Model_Git::formatDate($release->published_at) ?></li>
                            <li><a href="<?php print $release->html_url ?>" target="_blank">github</a></li>
                            <li><a href="<?php print $release->zipball_url ?>">.zip</a></li>
                            <li><a href="<?php print $release->tarball_url ?>">.tar.gz</a></li>
                        </ul>
                    </div>
                </div>
                <div class='notes formatted'>
                    <?php print Markdown($release->body); ?>
                </div>
            </div>

            <!--
            <pre>
            <?php 
                //print_r($release);  
            ?>
            </pre>
            -->

        <?php endforeach; ?>
    </div>
</div>
