<!--
<div id="download-latest" class="download">
    <h3>Download latest working build.</h3>
    <p>ARM Build X.X.XXX</p>
</div>
-->

<div id="download-svn" class="download">
    <h1>Repository</h1>
    <pre>svn checkout http://dashee.googlecode.com/svn/ dashee</pre>
    <p>Dashee's related code sit under <code>trunk</code> and the servers and clients are split in <code>trunk/server</code> and <code>trunk/client</code>. Follow our <a href="./wiki">Wiki</a> to get yourself started.</p>
</div>

<div id="download-bugtrack" class="download">
    <h3>Found a Bug?</h3>
    <p>
        Please let us know of any bugs with the system at <a href="https://code.google.com/p/dashee/issues/list" target="_blank">https://code.google.com/p/dashee/issues/list</a>.
    </p>
</div>
