<div class='download'>
    <div class='release-notes'>
        <h2>
            Relese notes for 
                <strong><?php print $this->releases[0]->name ?></strong>
                (<strong><?php print $this->releases[0]->tag_name ?></strong>)
        </h2>
        <div class='formatted'><?php print Markdown($this->releases[0]->body); ?></div>
    </div>
    <div class='releases'>
        <?php for ($x = 0; $x < count($this->releases); $x++): ?>
            <?php $release = $this->releases[$x]; ?>

            <div class='release'>
                <h1 class='name'>
                    <span class='name'><?php print $release->name; ?></span>
                    <span class='tag'>(<?php print $release->tag_name; ?>)</span> 
                </h1>
                <ul class='small-text'>
                    <li><a href="<?php print $release->html_url ?>" target="_blank">github</a></li>
                    <li><a href="<?php print $release->zipball_url ?>">.zip</a></li>
                    <li><a href="<?php print $release->tarball_url ?>">.tar.gz</a></li>
                </ul>
            </div>

            <!--
            <pre>
            <?php 
                print_r($release);  
            ?>
            </pre>
            -->

        <?php endfor; ?>
    </div>
</div>
