<div class='index'>
    <div class='formatted'>
        <p>Dashee provides a control framework for autonomous remote control vehicles. You can control a remote vehicle using protocols over 3G, WiFi or radio, using the recommended hardware. Dashee is built for multiple models such as Cars, Helicopters, QuadCopters and Planes. More specific modules can be extended by the contributors to achieve a wider availability of vehicles.</p>
        <p>Dashee, uses a client server model, where the client can pass instructions to the server and the server responds to those instructions. The server is also designed to make calculated autonomous decisions locally so it can operate without user instructions. For the server we use the RaspberryPi and for clients we have developed Android, Chrome and Joystick applications.</p>
        <p>We invite you to join us on <a href='http://github.com/dashee-bot/dashee' target='_blank'>http://github.com/dashee-bot/dashee</a> to help us further this fun little project. If you are looking to download source, look at our <a href='/downloads/'>downloads</a> page, and for help try the <a href='http://github.com/dashee-bot/dashee/wiki' target='_blank'>GitHub wiki</a></p>
    </div>
</div>
