<div class='issues'>

    <?php foreach ($this->issues as $issue): ?>
        
        <div class='issue'>
            <div class='number'>
                <?php if ($issue->state == "open"): ?>
                    <span class='open'>#<?php print $issue->number ?></span>
                <?php else: ?>
                    <span class='closed'>#<?php print $issue->number ?></span>
                <?php endif; ?>
            </div>
            <div class='info'>
                <h3>
                    <a href="<?php print $issue->html_url ?>" target="_blank">
                        <?php print $issue->title ?>
                    </a>
                </h3>
                <ul>
                    <?php foreach ($issue->labels as $label): ?>
                        <li class='label' style="background-color:#<?php print $label->color ?>">
                            <?php print $label->name ?>
                        </li>
                    <?php endforeach; ?>

                    <li class='text'>
                        Opened by 
                        <strong>
                            <a href='<?php print $issue->user->html_url ?>' target='_blank' title="Click to go to <?php print $issue->user->login ?>'s profile">
                                <?php print $issue->user->login ?>
                            </a>
                        </strong>
                    <?php if (isset($issue->milestone)): ?>
                        in <strong><?php print $issue->milestone->title; ?></strong>
                    <?php endif; ?>
                    <li>

                </ul>
            </div>
            <div class='assigned'>
                <?php if (isset($issue->assignee)): ?>
                    <div class='gravatar'>
                        <img src="http://www.gravatar.com/avatar/<?php print $issue->assignee->gravatar_id; ?>?s=32" />
                    </div>
                <?php endif; ?>
                    <div class='login'>
                        <div class='user'>
                            <?php if (isset($issue->assignee)): ?>
                                <a href='<?php print $issue->user->html_url ?>' target='_blank' title="Click to go to <?php print $issue->user->login ?>'s profile">
                                    <?php print $issue->assignee->login; ?>
                                </a>
                            <?php else: ?>
                                <?php print "Unassigned" ?>
                            <?php endif; ?>
                        </div>
                        <div class='posted-on'>
                            <?php print Application_Model_Git::formatDate($issue->created_at); ?>
                        </div>
                    </div>  
            </div>
        </div>

    <?php endforeach; ?>

    <!-- View all link -->
    <div class='viewall'>
        <div class='heading'>Found a problem? Create issues at:</div>
        <div class='link'>
            <a href='https://github.com/dashee-bot/dashee/issues?milestone=0' target='_blank'>https://github.com/dashee-bot/dashee/issues</a>
        </div>
    </div>

    <!--
    <pre>
    <?php 
        print_r($this->issues);  
    ?>
    </pre>
    -->
</div>
