<div id="deed-header" class="deed">
    <div class="logo">
        <a rel="nofollow" href="http://creativecommons.org/licenses/by-nc-sa/3.0/deed.en_GB"><img alt="Creative Commons Licence" src="http://i.creativecommons.org/l/by-nc-sa/3.0/88x31.png" align="left"/></a>
    </div>
    <div class="heading">
        <h1>Creative Commons Licence</h1>
        <p>Attribution-NonCommercial-ShareAlike 3.0 Unported</p>
    </div>
</div>
<div id="deed-disclaimer" class="deed">
    <p><strong>Disclaimer</strong> — The Commons Deed (Following text) is not a licence. It is simply a handy reference for understanding <a href="http://creativecommons.org/licenses/by-nc-sa/3.0/legalcode" target="_blank">the Legal Code (the full licence, Click to Download)</a> — it is a human-readable expression of some of its key terms. Think of it as the user-friendly interface to the Legal Code beneath. This Deed itself has no legal value, and its contents do not appear in the actual licence.
    </p>
</div>
<div id="deed-rights" class="deed">
    <h3 resource="http://creativecommons.org/ns#Reproduction" rel="cc:permits">You are free:</h3>
    <ul class="license-properties">
      <li class="license share" rel="cc:permits" resource="http://creativecommons.org/ns#Distribution">to copy, distribute, display, and perform the work</li>
      <li class="license remix" rel="cc:permits" resource="http://creativecommons.org/ns#DerivativeWorks">to make derivative works</li>      
    </ul>
</div>
<div id="deed-conditions" class="deed">
    <h3>Under the following conditions:</h3>
    <ul class="license-properties">
        <li class="license by" rel="cc:requires" resource="http://creativecommons.org/ns#Attribution">
            <p>
                <strong>Attribution</strong> — You must give dashee's author credit.
            </p>
        </li>
        <li class="license nc" rel="cc:prohibits" resource="http://creativecommons.org/ns#CommercialUse">
            <p>
                <strong>Non-Commercial</strong> — You may not use this dashee for commercial purposes without permission.
            </p>
        </li>
        <li class="license sa" rel="cc:requires" resource="http://creativecommons.org/ns#ShareAlike">
            <p>
                <strong>Share Alike</strong> — If you alter, transform, or build upon this work, you may distribute the resulting work only under a licence identical to this one.
            </p>
        </li>
    </ul>
</div>
<div id="deed-understanding" class="deed">
    <h3>With the understanding that:</h3>
    <ul class="understanding license-properties">
        <li class="license">
            <strong>Waiver</strong> — Any of the above conditions can be waived if you get permission from the copyright holder.
        </li>
        <li class="license">
            <strong>Public Domain</strong> — Where the work or any of its elements is in the <a href="http://wiki.creativecommons.org/Public_domain" target="_blank" id="public_domain" class="helpLink">public domain</a> under applicable law, that status is in no way affected by the licence.
        </li>
        <li class="license">
            <strong>Other Rights</strong> — In no way are any of the following rights affected by the licence:
                <ul>
                    <li>
                        Your fair dealing or <a href="http://wiki.creativecommons.org/Frequently_Asked_Questions#Do_Creative_Commons_licenses_affect_fair_use.2C_fair_dealing_or_other_exceptions_to_copyright.3F" target="_blank" id="fair_use" class="helpLink">fair use</a> rights, or other applicable copyright exceptions and limitations;
                    </li>
                    <li>
                        The author's <a href="http://wiki.creativecommons.org/Frequently_Asked_Questions#I_don.E2.80.99t_like_the_way_a_person_has_used_my_work_in_a_derivative_work_or_included_it_in_a_collective_work.3B_what_can_I_do.3F" target="_blank" id="moral_rights" class="helpLink">moral</a> rights;
                    </li>
                    <li>
                        Rights other persons may have either in the work itself or in how the work is used, such as <a href="http://wiki.creativecommons.org/Frequently_Asked_Questions#When_are_publicity_rights_relevant.3F" target="_blank" class="helpLink" id="publicity_rights">publicity</a> or privacy rights.
                    </li>
                </ul>
        </li>
        <li rel="cc:requires" resource="http://creativecommons.org/ns#Notice">
            <strong>Notice</strong> — For any reuse or distribution, you must make clear to others the licence terms of this work.
        </li>
    </ul>
    <div id="help_waived" class="help">
        <h4>What does "conditions can be waived" mean?</h4>
        <p>
            CC licenses anticipate that a licensor may want to waive compliance with a specific condition, such as attribution.
            <a href="http://wiki.creativecommons.org/Frequently_Asked_Questions#Can_I_change_the_terms_of_a_CC_license_or_waive_some_of_its_conditions.3F" target="_blank">Learn more</a>.
        </p>
    </div>
    <div id="help_public_domain" class="help">
      <h4>What does "Public Domain" mean?</h4>
        <p>
            A work is in the public domain when it is free for use by anyone for any purpose without restriction under copyright.
            <a href="http://wiki.creativecommons.org/Public_domain" target="_blank">Learn more</a>.
        </p>
    </div>
    <div id="help_fair_use" class="help">
      <h4>What does "Fair use" mean?</h4>
        <p>
            All jurisdictions
                allow some limited uses of copyrighted material without
                permission.  CC licenses do not affect the rights of
                users under those copyright limitations and exceptions,
                such as fair use and fair dealing where applicable.
            <a href="http://wiki.creativecommons.org/Frequently_Asked_Questions#Do_Creative_Commons_licenses_affect_fair_use.2C_fair_dealing_or_other_exceptions_to_copyright.3F" target="_blank">Learn more</a>.
        </p>
    </div>
    <div id="help_moral_rights" class="help">
      <h4>What are "Moral Rights"?</h4>
        <p>
            In addition to the right of licensors to request removal of their name from the work when used in a derivative or collective they don't like, copyright laws in most jurisdictions around the world (with the notable exception of the US except in very limited circumstances) grant creators "moral rights" which may provide some redress if a derivative work represents a "derogatory treatment" of the licensor's work.
            <a href="http://wiki.creativecommons.org/Frequently_Asked_Questions#I_don.E2.80.99t_like_the_way_a_person_has_used_my_work_in_a_derivative_work_or_included_it_in_a_collective_work.3B_what_can_I_do.3F" target="_blank">Learn more</a>.
        </p>
    </div>
    <div id="help_publicity_rights" class="help">
      <h4>What are "Publicity Rights"?</h4>
        <p>
            Publicity
            rights allow individuals to control how their voice,
            image or likeness is used for commercial purposes in
            public.  If a CC-licensed work includes the voice or
            image of anyone other than the licensor, a user of the
            work may need to get permission from those individuals
            before using the work for commercial purposes.
            <a href="http://wiki.creativecommons.org/Frequently_Asked_Questions#When_are_publicity_rights_relevant.3F" target="_blank">Learn more</a>.
        </p>
    </div>
  </div>
