<nav>
    <div class='logo'><a href='/'><img src='/images/logo/72px.fw.png' /></a></div>
    <div class='links'>
        <div><a href="/wiki">Wiki</a></div>
        <!--<div><a href="/about/">About</a></div>-->
        <div><a href="/downloads">Downloads</a></div>
        <div><a href="/issues">Issues</a></div>
        <div><a href="/videos">Videos</a></div>
        <div><a href="/license">License</a></div>
    </div>
</nav>
