<!DOCTYPE HTML>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <?php echo $this->headMeta() ?>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headLink() ?>
</head>
<body>
    <div>
        <div><?php echo $this->render('index/navigation.phtml') ?></div>
        <div><?php echo $this->layout()->content; ?></div>
    </div>
    <?php echo $this->inlineScript(); ?>
</body>
</html>
