<div id='error'>
    <div class='main'>
        <div class='code'><?php echo $this->errorcode; ?></div>
        <div class='message'><?php echo $this->message; ?></div>
    </div>

    <?php if (isset($this->exception)): ?>
        <p class='exception'><b><?php echo $this->exceptiontype; ?>:</b> <?php echo $this->exception->getMessage() ?></p>
        <pre class='stack'><?php echo $this->exception->getTraceAsString() ?></pre>
        <pre class='request'><?php echo $this->escape(var_export($this->request->getParams(), true)) ?></pre>
    <?php endif ?>
</div>
